<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Modal, message } from 'ant-design-vue'
import { Boxes, CheckCircle2, FileCode2, GitBranch, Package, Play, Plus, RefreshCw, Rocket, ScrollText, Settings2, Workflow } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import PipelineLogDrawer from '@/components/PipelineLogDrawer.vue'
import ResourceTable from '@/components/ResourceTable.vue'
import { useAuthStore } from '@/stores/auth'

type Section='applications'|'repositories'|'build-plans'|'image-registries'|'deployment-plans'|'release-plans'
const props=defineProps<{section:Section}>(),route=useRoute(),router=useRouter(),auth=useAuthStore()
interface Repository extends ResourceRecord{id:string;name:string;provider:string;clone_url:string;default_branch:string;webhook_enabled:boolean;webhook_url?:string;is_active:boolean;auth_type:string;username?:string;allow_insecure_http:boolean;has_credential?:boolean;credential_id?:string}
interface Credential{id:string;name:string;provider:string;auth_type:string;username?:string;secret_hint:string}
interface BuildPlan extends ResourceRecord{id:string;name:string;kind:string;description:string;dockerfile_path?:string;context_path:string;timeout_seconds:number;is_active:boolean}
interface Registry extends ResourceRecord{id:string;name:string;provider:string;endpoint:string;namespace:string;has_credential:boolean;is_active:boolean}
interface DeploymentPlan extends ResourceRecord{id:string;name:string;kind:string;description:string;helm_chart?:string;helm_values?:string;compose_file?:string;service_name?:string;script?:string;timeout_seconds:number;is_active:boolean}
interface WorkflowTemplate{id:string;name:string;revision:number;is_active:boolean}
interface Application extends ResourceRecord{id:string;name:string;description:string;repository_id:string;branch:string;poll_interval_seconds:number;build_plan_id?:string;image_registry_id?:string;deployment_plan_id?:string;workflow_template_id?:string;last_observed_commit?:string;sync_status:string;sync_message?:string;last_checked_at?:string;is_active:boolean;repository?:Repository;build_plan?:BuildPlan;image_registry?:Registry;deployment_plan?:DeploymentPlan;workflow_template?:WorkflowTemplate;workflow?:{is_active:boolean;revision:number}}
interface Run extends ResourceRecord{id:string;application_id:string;trigger:string;ref:string;commit_sha:string;commit_message?:string;status:string;stage:string;message?:string;created_at:string;updated_at?:string;application?:Application;environment?:string;current_node_id?:string;current_node_name?:string;created_by?:string;image?:string}
interface ReleasePlan extends ResourceRecord{id:string;name:string;version:string;description:string;status:string;created_at:string;groups?:Array<{id:string;name:string;mode:string;failure_policy:string;applications:Array<{application_id:string;application?:Application}>}>}
interface GitRef{name:string;sha:string} interface RefResult{branches:GitRef[];tags:GitRef[];manual_sources?:Array<{id:string;name:string;environment?:string}>}

const applications=ref<Application[]>([]),repositories=ref<Repository[]>([]),credentials=ref<Credential[]>([]),buildPlans=ref<BuildPlan[]>([]),registries=ref<Registry[]>([]),deploymentPlans=ref<DeploymentPlan[]>([]),workflowTemplates=ref<WorkflowTemplate[]>([]),runs=ref<Run[]>([]),releasePlans=ref<ReleasePlan[]>([]),deployments=ref<ResourceRecord[]>([])
const loading=ref(false),saving=ref(false),formOpen=ref(false),editingID=ref(''),registryTested=ref(false),testing=ref(false),manualOpen=ref(false),manualApplicationID=ref(''),commitOpen=ref(false),commitOptions=ref<Array<{ref:string;name:string;sha:string;kind:string}>>([]),selectedRef=ref(''),selectedSource=ref(''),manualSources=ref<Array<{id:string;name:string}>>([]),currentRun=ref<Run|null>(null),log=ref({open:false,runID:'',title:'',status:''})
let releaseTimer=0
const appForm=reactive({name:'',description:'',repository_id:'',branch:'main',poll_enabled:true,poll_interval_seconds:5,watch_push:true,watch_pull_request:true,watch_tags:true,tag_pattern:'v*',build_plan_id:'',image_registry_id:'',deployment_plan_id:'',deployment_target_id:'',workflow_template_id:''})
const repoForm=reactive({name:'',provider:'github',clone_url:'',default_branch:'main',auth_type:'none',username:'',credential_id:'',webhook_enabled:true,allow_insecure_http:false})
const buildForm=reactive({name:'',kind:'dockerfile',description:'',script:'',dockerfile_path:'Dockerfile',context_path:'.',artifact_path:'',timeout_seconds:1800})
const registryForm=reactive({name:'',provider:'harbor',endpoint:'https://',namespace:'',username:'',credential:'',allow_insecure_http:false})
const deployForm=reactive({name:'',kind:'helm',description:'',script:'',helm_chart:'',helm_values:'',compose_file:'docker-compose.yml',service_name:'',timeout_seconds:600})
const releaseForm=reactive({description:'',application_ids:[] as string[]})

const copy:Record<Section,{description:string}>={applications:{description:'一个应用对应一个代码仓库，并维护自己的构建、部署和流水线配置。'},repositories:{description:'统一管理 Git 来源和可选 Webhook；凭据来自当前用户自己的令牌。'},'build-plans':{description:'保存可复用的 Dockerfile 或脚本构建配置。'},'image-registries':{description:'管理 Harbor、Docker Hub 或其他 OCI Registry；保存前必须完成真实登录测试。'},'deployment-plans':{description:'定义部署节点如何通过 Helm、Docker Compose、Docker 或受控脚本执行。'},'release-plans':{description:'发布计划组织人工批量发布；流水线运行与发布记录独立展示。'}}
const releaseView=computed(()=>route.query.view==='runs'?'runs':route.query.view==='records'?'records':'plans')
const canManage=computed(()=>props.section==='repositories'?auth.canAny(['repository.manage']):auth.canAny(['delivery.manage']))
const currentDescription=computed(()=>props.section==='release-plans'?(releaseView.value==='runs'?'查看代码事件或手动操作触发的执行、当前节点和实时日志。':releaseView.value==='records'?'查看已经进入真实发布目标的部署结果。':copy[props.section].description):copy[props.section].description)
const activeRows=computed<ResourceRecord[]>(()=>props.section==='applications'?applications.value:props.section==='repositories'?repositories.value:props.section==='build-plans'?buildPlans.value:props.section==='image-registries'?registries.value:props.section==='deployment-plans'?deploymentPlans.value:[])
const activeColumns=computed(()=>props.section==='applications'?[{key:'name',label:'应用'},{key:'repository',label:'代码仓库'},{key:'build_plan',label:'构建方案'},{key:'deployment_plan',label:'部署方案'},{key:'sync_status',label:'代码状态'},{key:'last_checked_at',label:'最近检查'}]:props.section==='repositories'?[{key:'name',label:'名称'},{key:'provider',label:'平台'},{key:'clone_url',label:'Clone 地址'},{key:'default_branch',label:'默认分支'},{key:'webhook_enabled',label:'Webhook'},{key:'is_active',label:'状态'}]:props.section==='build-plans'?[{key:'name',label:'名称'},{key:'kind',label:'类型'},{key:'description',label:'说明'},{key:'context_path',label:'构建上下文'},{key:'timeout_seconds',label:'超时'}]:props.section==='image-registries'?[{key:'name',label:'名称'},{key:'provider',label:'类型'},{key:'endpoint',label:'地址'},{key:'namespace',label:'命名空间'},{key:'has_credential',label:'凭据'}]:[{key:'name',label:'名称'},{key:'kind',label:'部署方式'},{key:'description',label:'说明'},{key:'timeout_seconds',label:'超时'}])

async function refresh(){loading.value=true;try{const requests=await Promise.all([auth.canAny(['delivery.read'])?client.get<{applications:Application[]}>('/applications'):null,auth.canAny(['repository.read'])?client.get<{repositories:Repository[]}>('/repositories'):null,auth.canAny(['credential.read'])?client.get<{credentials:Credential[]}>('/git-credentials'):null,auth.canAny(['delivery.read'])?client.get<{build_plans:BuildPlan[]}>('/build-plans'):null,auth.canAny(['delivery.read'])?client.get<{image_registries:Registry[]}>('/image-registries'):null,auth.canAny(['delivery.read'])?client.get<{deployment_plans:DeploymentPlan[]}>('/deployment-plans'):null,auth.canAny(['delivery.read'])?client.get<{workflow_templates:WorkflowTemplate[]}>('/workflow-templates'):null,auth.canAny(['delivery.read'])?client.get<{pipeline_runs:Run[]}>('/pipeline-runs?limit=200'):null,auth.canAny(['delivery.read'])?client.get<{release_plans:ReleasePlan[]}>('/release-plans'):null,auth.canAny(['deployment.read'])?client.get<{deployments:ResourceRecord[]}>('/deployments'):null]);applications.value=requests[0]?.data.applications||[];repositories.value=requests[1]?.data.repositories||[];credentials.value=requests[2]?.data.credentials||[];buildPlans.value=requests[3]?.data.build_plans||[];registries.value=requests[4]?.data.image_registries||[];deploymentPlans.value=requests[5]?.data.deployment_plans||[];workflowTemplates.value=requests[6]?.data.workflow_templates||[];runs.value=requests[7]?.data.pipeline_runs||[];releasePlans.value=requests[8]?.data.release_plans||[];deployments.value=requests[9]?.data.deployments||[]}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
function resetForms(){editingID.value='';registryTested.value=false;Object.assign(appForm,{name:'',description:'',repository_id:'',branch:'main',poll_enabled:true,poll_interval_seconds:5,watch_push:true,watch_pull_request:true,watch_tags:true,tag_pattern:'v*',build_plan_id:'',image_registry_id:'',deployment_plan_id:'',deployment_target_id:'',workflow_template_id:''});Object.assign(repoForm,{name:'',provider:'github',clone_url:'',default_branch:'main',auth_type:'none',username:'',credential_id:'',webhook_enabled:true,allow_insecure_http:false});Object.assign(buildForm,{name:'',kind:'dockerfile',description:'',script:'',dockerfile_path:'Dockerfile',context_path:'.',artifact_path:'',timeout_seconds:1800});Object.assign(registryForm,{name:'',provider:'harbor',endpoint:'https://',namespace:'',username:'',credential:'',allow_insecure_http:false});Object.assign(deployForm,{name:'',kind:'helm',description:'',script:'',helm_chart:'',helm_values:'',compose_file:'docker-compose.yml',service_name:'',timeout_seconds:600});Object.assign(releaseForm,{description:'',application_ids:[]})}
function create(){resetForms();formOpen.value=true}
function edit(row:ResourceRecord){editingID.value=String(row.id);if(props.section==='applications'){const item=row as Application;Object.assign(appForm,{name:item.name,description:item.description||'',repository_id:item.repository_id,branch:item.branch||'main',poll_enabled:true,poll_interval_seconds:item.poll_interval_seconds||5,watch_push:true,watch_pull_request:true,watch_tags:true,tag_pattern:'v*',build_plan_id:item.build_plan_id||'',image_registry_id:item.image_registry_id||'',deployment_plan_id:item.deployment_plan_id||'',deployment_target_id:'',workflow_template_id:item.workflow_template_id||''})}if(props.section==='repositories'){const item=row as Repository;Object.assign(repoForm,{name:item.name,provider:item.provider,clone_url:item.clone_url,default_branch:item.default_branch,auth_type:item.auth_type,username:item.username||'',credential_id:item.credential_id||'',webhook_enabled:item.webhook_enabled,allow_insecure_http:item.allow_insecure_http})}if(props.section==='deployment-plans'){const item=row as DeploymentPlan;Object.assign(deployForm,{name:item.name,kind:item.kind,description:item.description||'',script:item.script||'',helm_chart:item.helm_chart||'',helm_values:item.helm_values||'',compose_file:item.compose_file||'docker-compose.yml',service_name:item.service_name||'',timeout_seconds:item.timeout_seconds||600})}formOpen.value=true}
async function save(){saving.value=true;try{let endpoint='',payload:unknown={},method:'post'|'put'='post';if(props.section==='applications'){endpoint=editingID.value?`/applications/${editingID.value}`:'/applications';payload={...appForm,environments:[]};method=editingID.value?'put':'post'}if(props.section==='repositories'){endpoint=editingID.value?`/repositories/${editingID.value}`:'/repositories';payload={...repoForm,credential_id:repoForm.auth_type==='none'?null:repoForm.credential_id||null,regenerate_webhook:false};method=editingID.value?'put':'post'}if(props.section==='build-plans'){endpoint='/build-plans';payload=buildForm}if(props.section==='image-registries'){if(!registryTested.value){message.error('请先测试镜像仓库登录');return}endpoint='/image-registries';payload={...registryForm,credential:registryForm.credential||null}}if(props.section==='deployment-plans'){endpoint=editingID.value?`/deployment-plans/${editingID.value}`:'/deployment-plans';payload=deployForm;method=editingID.value?'put':'post'}if(props.section==='release-plans'){if(!releaseForm.application_ids.length){message.error('请至少选择一个应用');return}endpoint='/release-plans';payload={description:releaseForm.description,applications:releaseForm.application_ids.map(application_id=>({application_id,manual_deploy:false,source_type:'',source_value:''}))}}await client[method](endpoint,payload);message.success('配置已保存');formOpen.value=false;resetForms();await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
async function testRepository(){testing.value=true;try{const payload={...repoForm,credential_id:repoForm.auth_type==='none'?null:repoForm.credential_id||null,credential:null,regenerate_webhook:false};const result=editingID.value?await client.post<RefResult>(`/repositories/${editingID.value}/test`,undefined,{timeout:35000}):await client.post<RefResult>('/repositories/test',payload,{timeout:35000});message.success(`连接成功：${result.data.branches?.length||0} 个分支，${result.data.tags?.length||0} 个标签`)}catch(error){message.error(apiErrorMessage(error))}finally{testing.value=false}}
async function testRegistry(){testing.value=true;registryTested.value=false;try{await client.post('/image-registries/test',{...registryForm,credential:registryForm.credential||null},{timeout:35000});registryTested.value=true;message.success('镜像仓库登录成功')}catch(error){message.error(apiErrorMessage(error))}finally{testing.value=false}}
async function action(path:string){try{await client.post(path,undefined,{timeout:35000});await refresh()}catch(error){message.error(apiErrorMessage(error))}}
function openLogs(run:Run){log.value={open:true,runID:run.id,title:`${applications.value.find(item=>item.id===run.application_id)?.name||'应用'} · 流水线日志`,status:run.status}}
function openManual(){manualApplicationID.value=applications.value.find(item=>item.is_active)?.id||'';manualOpen.value=true}
async function nextManual(){if(!manualApplicationID.value)return;saving.value=true;try{currentRun.value=(await client.post<{pipeline_run:Run}>(`/applications/${manualApplicationID.value}/pipeline-runs`)).data.pipeline_run;const data=(await client.get<RefResult>(`/applications/${manualApplicationID.value}/repository-refs`,{timeout:35000})).data;commitOptions.value=[...(data.branches||[]).map(item=>({ref:`refs/heads/${item.name}`,name:item.name,sha:item.sha,kind:'分支'})),...(data.tags||[]).map(item=>({ref:`refs/tags/${item.name}`,name:item.name,sha:item.sha,kind:'Tag'}))];manualSources.value=(data.manual_sources||[]).map(item=>({id:item.id,name:item.name}));selectedRef.value=commitOptions.value[0]?.ref||'';selectedSource.value=manualSources.value[0]?.id||'';manualOpen.value=false;commitOpen.value=true}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
async function executeCommit(){const selected=commitOptions.value.find(item=>item.ref===selectedRef.value);if(!selected||!currentRun.value)return;saving.value=true;try{await client.post(`/pipeline-runs/${currentRun.value.id}/execute`,{ref:selected.ref,commit_sha:selected.sha,source_node_id:selectedSource.value});message.success('流水线已开始执行');commitOpen.value=false;await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
function removeRun(run:Run){Modal.confirm({title:'删除这次流水线运行？',content:'运行数据无法恢复，独立发布记录不会删除。',okType:'danger',async onOk(){try{await client.delete(`/pipeline-runs/${run.id}`);await refresh()}catch(error){message.error(apiErrorMessage(error))}}})}
function showWebhook(item:Repository){void client.get<{webhook_url:string;webhook_secret:string}>(`/repositories/${item.id}/webhook`).then(result=>Modal.info({title:`${item.name} Webhook`,width:650,content:()=>`${result.data.webhook_url}\n${result.data.webhook_secret}`})).catch(error=>message.error(apiErrorMessage(error)))}
function selectReleaseView(view:string){void router.replace({query:{view}})}
function linkedName(row:ResourceRecord,key:'repository'|'build_plan'|'deployment_plan'){return (row as Application)[key]?.name||'未绑定'}

watch(()=>props.section,()=>{formOpen.value=false;resetForms();void refresh()})
watch(()=>registryForm,()=>registryTested.value=false,{deep:true})
onMounted(()=>{void refresh();releaseTimer=window.setInterval(()=>{if(props.section==='release-plans'&&!document.hidden)void refresh()},4000)})
onBeforeUnmount(()=>clearInterval(releaseTimer))
</script>

<template><section><PageToolbar :description="currentDescription"><a-tag v-if="props.section==='release-plans'" color="processing">自动更新</a-tag><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button><a-button v-if="props.section==='release-plans'&&releaseView==='runs'&&auth.canAny(['delivery.run'])" type="primary" @click="openManual"><Play :size="15"/>手动执行</a-button><a-button v-else-if="canManage&&(props.section!=='release-plans'||releaseView==='plans')" type="primary" @click="create"><Plus :size="15"/>{{ props.section==='release-plans'?'创建发布计划':'新建' }}</a-button></PageToolbar>
<a-segmented v-if="props.section==='release-plans'" :value="releaseView" :options="[{value:'plans',label:'发布计划'},{value:'runs',label:'流水线运行'},{value:'records',label:'发布记录'}]" class="release-tabs" @change="(value:string)=>selectReleaseView(value)"/>
<div v-if="props.section!=='release-plans'" class="vben-card"><ResourceTable :rows="activeRows" :columns="activeColumns" :loading="loading"><template #cell-repository="{row}">{{ linkedName(row,'repository') }}</template><template #cell-build_plan="{row}">{{ linkedName(row,'build_plan') }}</template><template #cell-deployment_plan="{row}">{{ linkedName(row,'deployment_plan') }}</template><template #cell-sync_status="{value}"><a-tag :color="value==='changed'?'warning':value==='synced'?'success':'default'">{{ value }}</a-tag></template><template #cell-kind="{value}"><a-tag color="blue">{{ value }}</a-tag></template><template #cell-timeout_seconds="{value}">{{ value }} 秒</template><template #actions="{row}"><a-button v-if="canManage&&(props.section==='applications'||props.section==='repositories'||props.section==='deployment-plans')" type="link" @click="edit(row)">编辑</a-button><a-button v-if="props.section==='applications'&&auth.canAny(['delivery.manage'])" type="link" @click="action(`/applications/${row.id}/check`)">检查更新</a-button><a-button v-if="props.section==='applications'" type="link" @click="router.push(`/pipeline-plans/editor?application=${row.id}`)">流水线</a-button><a-button v-if="props.section==='repositories'" type="link" @click="action(`/repositories/${row.id}/test`)">测试</a-button><a-button v-if="props.section==='repositories'&&auth.canAny(['repository.secret.read'])" type="link" @click="showWebhook(row as Repository)">Webhook</a-button></template></ResourceTable></div>
<div v-else-if="releaseView==='runs'" class="run-list"><article v-for="run in runs" :key="run.id" class="run-card vben-card"><span class="run-dot" :class="run.status"/><div><header><h3>{{ applications.find(item=>item.id===run.application_id)?.name||run.application?.name||'未命名应用' }}</h3><a-tag :color="run.status==='succeeded'?'success':run.status==='failed'||run.status==='blocked'?'error':run.status==='running'?'processing':'warning'">{{ run.status }}</a-tag></header><div class="run-commit"><strong>{{ run.commit_message||'未记录提交说明' }}</strong><span>{{ run.ref?.replace(/^refs\/(heads|tags)\//,'')||'未选择分支' }} · <code>{{ run.commit_sha?.slice(0,8)||'—' }}</code></span></div><dl><div><dt>当前节点</dt><dd>{{ run.current_node_name||run.current_node_id||'尚未开始' }}</dd></div><div><dt>环境</dt><dd>{{ run.environment||'—' }}</dd></div><div><dt>创建时间</dt><dd>{{ new Date(run.created_at).toLocaleString('zh-CN',{hour12:false}) }}</dd></div></dl><footer><a-button @click="openLogs(run)">查看日志</a-button><a-button v-if="run.status==='failed'&&auth.canAny(['delivery.run'])" type="primary" @click="action(`/pipeline-runs/${run.id}/retry`)">重新执行</a-button><a-button v-if="run.status==='awaiting_approval'&&auth.canAny(['deployment.review'])" type="primary" @click="action(`/pipeline-runs/${run.id}/approve`)">通过审核</a-button><a-button v-if="run.stage==='manual'&&auth.canAny(['delivery.run'])" type="primary" @click="action(`/pipeline-runs/${run.id}/advance`)">放行并继续</a-button><a-button v-if="auth.canAny(['delivery.manage'])" danger @click="removeRun(run)">删除</a-button></footer></div></article><a-empty v-if="!runs.length&&!loading" description="还没有流水线运行"/></div>
<div v-else-if="releaseView==='records'" class="vben-card"><ResourceTable :rows="deployments" :loading="loading" :columns="[{key:'environment',label:'环境'},{key:'operation',label:'操作'},{key:'image',label:'镜像'},{key:'status',label:'状态'},{key:'requested_by',label:'申请人'},{key:'approved_by',label:'审核人'},{key:'error_message',label:'失败原因'},{key:'created_at',label:'时间'}]"/></div>
<div v-else class="plan-grid"><article v-for="plan in releasePlans" :key="plan.id" class="plan-card vben-card"><header><div><h3>{{ plan.description||plan.name||'发布计划' }}</h3><span>{{ new Date(plan.created_at).toLocaleString('zh-CN',{hour12:false}) }}</span></div><a-tag :color="plan.status==='active'?'processing':plan.status==='completed'?'success':'default'">{{ plan.status }}</a-tag></header><div v-for="group in plan.groups||[]" :key="group.id" class="plan-group"><strong>{{ group.name }}</strong><span>{{ group.mode==='parallel'?'组内并行':'组内串行' }} · {{ group.failure_policy }}</span><div><a-tag v-for="item in group.applications||[]" :key="item.application_id">{{ item.application?.name||applications.find(app=>app.id===item.application_id)?.name||item.application_id }}</a-tag></div></div><a-empty v-if="!plan.groups?.length" :image="null" description="尚未配置发布组"/></article><a-empty v-if="!releasePlans.length&&!loading" description="还没有发布计划"/></div>

<a-drawer v-model:open="formOpen" :title="editingID?'编辑配置':props.section==='release-plans'?'创建发布计划':'新建配置'" width="700"><a-form layout="vertical">
<template v-if="props.section==='applications'"><div class="form-grid"><a-form-item label="应用名称" required><a-input v-model:value="appForm.name"/></a-form-item><a-form-item label="说明"><a-input v-model:value="appForm.description"/></a-form-item><a-form-item class="span2" label="代码仓库" required><a-select v-model:value="appForm.repository_id" show-search :options="repositories.filter(item=>item.is_active).map(item=>({value:item.id,label:`${item.name} · ${item.default_branch}`}))"/></a-form-item><a-form-item label="构建方案" required><a-select v-model:value="appForm.build_plan_id" :options="buildPlans.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/></a-form-item><a-form-item label="部署方案" required><a-select v-model:value="appForm.deployment_plan_id" :options="deploymentPlans.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/></a-form-item><a-form-item label="镜像仓库"><a-select v-model:value="appForm.image_registry_id" allow-clear :options="registries.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/></a-form-item><a-form-item label="流水线方案" required><a-select v-model:value="appForm.workflow_template_id" :options="workflowTemplates.filter(item=>item.is_active).map(item=>({value:item.id,label:`${item.name} · 第 ${item.revision} 版`}))"/></a-form-item><a-form-item label="检查间隔"><a-select v-model:value="appForm.poll_interval_seconds" :options="[3,5,10,60].map(value=>({value,label:`${value} 秒`}))"/></a-form-item></div></template>
<template v-if="props.section==='repositories'"><div class="form-grid"><a-form-item label="名称" required><a-input v-model:value="repoForm.name"/></a-form-item><a-form-item label="平台"><a-select v-model:value="repoForm.provider" :options="['github','gitlab','gitea','gitee','generic'].map(value=>({value,label:value}))"/></a-form-item><a-form-item class="span2" label="Clone 地址" required><a-input v-model:value="repoForm.clone_url"/></a-form-item><a-form-item label="默认分支"><a-input v-model:value="repoForm.default_branch"/></a-form-item><a-form-item label="认证方式"><a-select v-model:value="repoForm.auth_type" :options="[{value:'none',label:'无需认证'},{value:'token',label:'访问令牌'},{value:'ssh_key',label:'SSH 私钥'}]"/></a-form-item><a-form-item v-if="repoForm.auth_type!=='none'" class="span2" label="我的令牌"><a-select v-model:value="repoForm.credential_id" :options="credentials.filter(item=>item.auth_type===repoForm.auth_type).map(item=>({value:item.id,label:`${item.name} · ${item.secret_hint}`}))"/><small>仓库只能引用当前操作者自己的令牌。</small></a-form-item><a-checkbox v-model:checked="repoForm.webhook_enabled">启用 Webhook</a-checkbox></div></template>
<template v-if="props.section==='build-plans'"><div class="form-grid"><a-form-item label="名称" required><a-input v-model:value="buildForm.name"/></a-form-item><a-form-item label="类型"><a-select v-model:value="buildForm.kind" :options="[{value:'dockerfile',label:'Dockerfile'},{value:'script',label:'打包脚本'}]"/></a-form-item><a-form-item class="span2" label="说明"><a-input v-model:value="buildForm.description"/></a-form-item><template v-if="buildForm.kind==='dockerfile'"><a-form-item label="Dockerfile 路径"><a-input v-model:value="buildForm.dockerfile_path"/></a-form-item><a-form-item label="构建上下文"><a-input v-model:value="buildForm.context_path"/></a-form-item></template><a-form-item v-else class="span2" label="打包脚本"><a-textarea v-model:value="buildForm.script" :rows="8"/></a-form-item><a-form-item label="超时（秒）"><a-input-number v-model:value="buildForm.timeout_seconds" :min="30" :max="7200"/></a-form-item></div></template>
<template v-if="props.section==='image-registries'"><div class="form-grid"><a-form-item label="名称" required><a-input v-model:value="registryForm.name"/></a-form-item><a-form-item label="类型"><a-select v-model:value="registryForm.provider" :options="[{value:'harbor',label:'Harbor'},{value:'docker_hub',label:'Docker Hub'},{value:'generic',label:'通用 Registry'}]"/></a-form-item><a-form-item class="span2" label="地址"><a-input v-model:value="registryForm.endpoint"/></a-form-item><a-form-item label="命名空间"><a-input v-model:value="registryForm.namespace"/></a-form-item><a-form-item label="用户名"><a-input v-model:value="registryForm.username"/></a-form-item><a-form-item class="span2" label="密码或 Token"><a-input-password v-model:value="registryForm.credential"/></a-form-item><a-checkbox v-model:checked="registryForm.allow_insecure_http">允许 HTTP（仅可信内网）</a-checkbox></div><a-alert v-if="registryTested" type="success" show-icon message="镜像仓库登录测试成功"/></template>
<template v-if="props.section==='deployment-plans'"><div class="form-grid"><a-form-item label="名称"><a-input v-model:value="deployForm.name"/></a-form-item><a-form-item label="部署方式"><a-select v-model:value="deployForm.kind" :options="[{value:'helm',label:'Helm'},{value:'compose',label:'Docker Compose'},{value:'docker',label:'Docker'},{value:'script',label:'自定义脚本'}]"/></a-form-item><a-form-item class="span2" label="说明"><a-input v-model:value="deployForm.description"/></a-form-item><a-form-item v-if="deployForm.kind==='helm'" class="span2" label="Chart 路径"><a-input v-model:value="deployForm.helm_chart"/></a-form-item><a-form-item v-if="deployForm.kind==='compose'" class="span2" label="Compose 文件"><a-input v-model:value="deployForm.compose_file"/></a-form-item><a-form-item v-if="deployForm.kind==='docker'" class="span2" label="Docker 工作负载名称"><a-input v-model:value="deployForm.service_name"/></a-form-item><a-form-item v-if="deployForm.kind==='script'" class="span2" label="部署脚本"><a-textarea v-model:value="deployForm.script" :rows="8"/></a-form-item><a-form-item label="超时（秒）"><a-input-number v-model:value="deployForm.timeout_seconds" :min="30" :max="3600"/></a-form-item></div></template>
<template v-if="props.section==='release-plans'"><a-form-item label="说明" required><a-textarea v-model:value="releaseForm.description" :rows="3"/></a-form-item><a-form-item label="应用" required><a-select v-model:value="releaseForm.application_ids" mode="multiple" :options="applications.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/><small>创建计划时至少选择一个应用。手动部署需在发布组中为每个应用指定分支或 Commit。</small></a-form-item></template>
<div class="drawer-actions"><a-button v-if="props.section==='repositories'" :loading="testing" @click="testRepository">测试连接</a-button><a-button v-if="props.section==='image-registries'" :loading="testing" @click="testRegistry">测试登录</a-button><a-button type="primary" :loading="saving" :disabled="props.section==='image-registries'&&!registryTested" @click="save">保存</a-button></div></a-form></a-drawer>
<a-modal v-model:open="manualOpen" title="手动执行流水线" :confirm-loading="saving" ok-text="下一步" @ok="nextManual"><a-form layout="vertical"><a-form-item label="应用"><a-select v-model:value="manualApplicationID" :options="applications.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/></a-form-item></a-form></a-modal>
<a-modal v-model:open="commitOpen" title="选择代码版本" :confirm-loading="saving" ok-text="确认并执行" @ok="executeCommit"><a-form layout="vertical"><a-form-item v-if="manualSources.length" label="流水线入口"><a-select v-model:value="selectedSource" :options="manualSources.map(item=>({value:item.id,label:item.name}))"/></a-form-item><a-form-item label="分支或 Tag"><a-select v-model:value="selectedRef"><a-select-opt-group label="分支"><a-select-option v-for="item in commitOptions.filter(item=>item.kind==='分支')" :key="item.ref" :value="item.ref">{{ item.name }} · {{ item.sha.slice(0,8) }}</a-select-option></a-select-opt-group><a-select-opt-group label="Tag"><a-select-option v-for="item in commitOptions.filter(item=>item.kind==='Tag')" :key="item.ref" :value="item.ref">{{ item.name }} · {{ item.sha.slice(0,8) }}</a-select-option></a-select-opt-group></a-select></a-form-item></a-form></a-modal>
<PipelineLogDrawer v-model:open="log.open" :runID="log.runID" :title="log.title" :initial-status="log.status"/>
</section></template>

<style scoped>.release-tabs{margin-bottom:12px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.span2{grid-column:1/-1}.drawer-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.run-list,.plan-grid{display:grid;gap:12px}.run-card{display:grid;grid-template-columns:10px 1fr;gap:13px;padding:17px}.run-dot{width:9px;height:9px;margin-top:6px;border-radius:50%;background:#a5aab3}.run-dot.running{background:#4f7df3;box-shadow:0 0 0 5px rgb(79 125 243 / 10%)}.run-dot.succeeded{background:#2ab573}.run-dot.failed,.run-dot.blocked{background:#ed5965}.run-card header{display:flex;align-items:center;justify-content:space-between}.run-card h3{margin:0}.run-commit{display:flex;justify-content:space-between;gap:16px;margin:12px 0}.run-commit span{color:var(--zrt-muted)}.run-card dl{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin:0;background:var(--zrt-border)}.run-card dl>div{padding:10px;background:var(--zrt-surface-soft)}.run-card dt{color:var(--zrt-muted);font-size:11px}.run-card dd{margin:3px 0 0}.run-card footer{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.plan-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.plan-card{padding:18px}.plan-card>header{display:flex;align-items:center;justify-content:space-between}.plan-card h3,.plan-card header span{margin:0}.plan-card header span{color:var(--zrt-muted);font-size:11px}.plan-group{margin-top:12px;padding:12px;border:1px solid var(--zrt-border);border-radius:7px}.plan-group>strong,.plan-group>span{display:block}.plan-group>span{color:var(--zrt-muted);font-size:11px}.plan-group>div{margin-top:8px}@media(max-width:760px){.form-grid,.plan-grid{grid-template-columns:1fr}.span2{grid-column:auto}.run-card dl{grid-template-columns:1fr}.run-commit{flex-direction:column}}
</style>
