<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Modal, message } from 'ant-design-vue'
import { Globe2, Plus, RefreshCw, Search } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import ResourceTable from '@/components/ResourceTable.vue'
import { useAuthStore } from '@/stores/auth'

interface ProviderField{key:string;label:string;secret:boolean;required:boolean;default?:string;placeholder?:string;help?:string;multiline?:boolean}
interface DNSProvider{code:string;name:string;description:string;fields:ProviderField[]}
interface DNSAccount extends ResourceRecord{id:string;name:string;provider:string;config:Record<string,string>;configured_secret_fields:string[];is_active:boolean;updated_at:string}
interface Domain extends ResourceRecord{id:string;account_id:string;account_name:string;provider:string;name:string;description:string;is_active:boolean;updated_at:string}
interface DNSRecord extends ResourceRecord{id:string;name:string;fqdn:string;type:string;value:string;ttl:number;read_only:boolean}
const auth=useAuthStore(),tab=ref<'domains'|'accounts'>('domains'),providers=ref<DNSProvider[]>([]),accounts=ref<DNSAccount[]>([]),domains=ref<Domain[]>([]),records=ref<DNSRecord[]>([]),selectedID=ref(''),query=ref(''),loading=ref(false),recordsLoading=ref(false),saving=ref(false),testingID=ref('')
const accountOpen=ref(false),domainOpen=ref(false),recordOpen=ref(false),editingAccountID=ref(''),editingDomainID=ref(''),editingRecordID=ref('')
const accountForm=reactive({name:'',provider:'',config:{} as Record<string,string>}),domainForm=reactive({account_id:'',name:'',description:''}),recordForm=reactive({name:'',type:'A',value:'',ttl:300})
const selectedDomain=computed(()=>domains.value.find(item=>item.id===selectedID.value)),selectedProvider=computed(()=>providers.value.find(item=>item.code===accountForm.provider)),filteredRecords=computed(()=>{const value=query.value.trim().toLowerCase();return value?records.value.filter(item=>`${item.name} ${item.fqdn} ${item.type} ${item.value}`.toLowerCase().includes(value)):records.value})
const accountColumns=[{key:'name',label:'账号名称'},{key:'provider',label:'厂商'},{key:'configured_secret_fields',label:'加密凭据'},{key:'is_active',label:'状态'},{key:'updated_at',label:'更新时间'}]
const domainColumns=[{key:'name',label:'域名'},{key:'account_name',label:'厂商账号'},{key:'provider',label:'厂商'},{key:'description',label:'说明'},{key:'is_active',label:'状态'}]
const recordColumns=[{key:'name',label:'主机记录'},{key:'type',label:'类型'},{key:'value',label:'记录值'},{key:'ttl',label:'TTL'},{key:'read_only',label:'只读'}]
const recordTypes=['A','AAAA','CNAME','MX','TXT','CAA','SRV','NS','PTR','HTTPS','SVCB','TLSA','URI','NAPTR','SSHFP']

async function refresh(){loading.value=true;try{const [p,a,d]=await Promise.all([client.get<{providers:DNSProvider[]}>('/dns/providers'),client.get<{accounts:DNSAccount[]}>('/dns/accounts'),client.get<{domains:Domain[]}>('/dns/domains')]);providers.value=p.data.providers;accounts.value=a.data.accounts;domains.value=d.data.domains;if(!domains.value.some(item=>item.id===selectedID.value))selectedID.value=domains.value[0]?.id||''}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
async function loadRecords(){if(!selectedID.value){records.value=[];return}recordsLoading.value=true;try{records.value=(await client.get<{records:DNSRecord[]}>(`/dns/domains/${selectedID.value}/records`,{timeout:35000})).data.records}catch(error){records.value=[];message.error(apiErrorMessage(error))}finally{recordsLoading.value=false}}
function newAccount(){editingAccountID.value='';const provider=providers.value[0];Object.assign(accountForm,{name:'',provider:provider?.code||'',config:Object.fromEntries((provider?.fields||[]).map(item=>[item.key,item.default||'']))});accountOpen.value=true}
function changeProvider(code:string){accountForm.provider=code;const provider=providers.value.find(item=>item.code===code);accountForm.config=Object.fromEntries((provider?.fields||[]).map(item=>[item.key,item.default||'']))}
function editAccount(item:DNSAccount){editingAccountID.value=item.id;Object.assign(accountForm,{name:item.name,provider:item.provider,config:{...item.config}});selectedProvider.value?.fields.forEach(field=>{if(!(field.key in accountForm.config))accountForm.config[field.key]=field.default||''});accountOpen.value=true}
async function saveAccount(){saving.value=true;try{const payload={...accountForm,clear_secret_fields:[]};if(editingAccountID.value)await client.put(`/dns/accounts/${editingAccountID.value}`,payload);else await client.post('/dns/accounts',payload);message.success('DNS 厂商账号已保存');accountOpen.value=false;await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
function newDomain(){editingDomainID.value='';Object.assign(domainForm,{account_id:accounts.value.find(item=>item.is_active)?.id||'',name:'',description:''});domainOpen.value=true}
function editDomain(item:Domain){editingDomainID.value=item.id;Object.assign(domainForm,{account_id:item.account_id,name:item.name,description:item.description});domainOpen.value=true}
async function saveDomain(){saving.value=true;try{const result=editingDomainID.value?await client.put<{domain:Domain}>(`/dns/domains/${editingDomainID.value}`,domainForm):await client.post<{domain:Domain}>('/dns/domains',domainForm);message.success('域名配置已保存');selectedID.value=result.data.domain.id;domainOpen.value=false;await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
async function testDomain(item:Domain){testingID.value=item.id;try{const result=(await client.post<{record_count:number}>(`/dns/domains/${item.id}/test`,undefined,{timeout:35000})).data;message.success(`连接成功，读取到 ${result.record_count} 条解析记录`);if(item.id===selectedID.value)await loadRecords()}catch(error){message.error(apiErrorMessage(error))}finally{testingID.value=''}}
async function toggle(kind:'account'|'domain',item:DNSAccount|Domain){try{await client.patch(`/dns/${kind==='account'?'accounts':'domains'}/${item.id}/status`,{active:!item.is_active});await refresh()}catch(error){message.error(apiErrorMessage(error))}}
function remove(kind:'account'|'domain',item:DNSAccount|Domain){Modal.confirm({title:`移除“${item.name}”？`,content:kind==='domain'?'只移除 EDO 引用，不删除厂商侧 Zone 和记录。':'使用中的厂商账号不能删除。',okType:'danger',async onOk(){try{await client.delete(`/dns/${kind==='account'?'accounts':'domains'}/${item.id}`);await refresh()}catch(error){message.error(apiErrorMessage(error))}}})}
function newRecord(){editingRecordID.value='';Object.assign(recordForm,{name:'',type:'A',value:'',ttl:300});recordOpen.value=true}
function editRecord(item:DNSRecord){editingRecordID.value=item.id;Object.assign(recordForm,{name:item.name,type:item.type,value:item.value,ttl:item.ttl});recordOpen.value=true}
async function saveRecord(){saving.value=true;try{if(editingRecordID.value)await client.put(`/dns/domains/${selectedID.value}/records/${editingRecordID.value}`,recordForm,{timeout:35000});else await client.post(`/dns/domains/${selectedID.value}/records`,recordForm,{timeout:35000});message.success('解析记录已保存');recordOpen.value=false;await loadRecords()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
function removeRecord(item:DNSRecord){Modal.confirm({title:`删除 ${item.fqdn} 的 ${item.type} 记录？`,content:'此操作会立即修改厂商侧 DNS。',okType:'danger',async onOk(){try{await client.delete(`/dns/domains/${selectedID.value}/records/${item.id}`,{timeout:35000});await loadRecords()}catch(error){message.error(apiErrorMessage(error))}}})}
watch(selectedID,()=>void loadRecords())
onMounted(refresh)
</script>

<template><section><PageToolbar description="统一管理不同 DNS 厂商的权威 Zone 和解析记录；凭据加密保存，变更写入审计日志。"><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button><a-button v-if="auth.canAny(['dns.manage'])" type="primary" @click="tab==='accounts'?newAccount():newDomain()"><Plus :size="15"/>{{ tab==='accounts'?'厂商账号':'添加域名' }}</a-button></PageToolbar><div class="dns-summary"><div><strong>{{ domains.length }}</strong><span>已接入域名</span></div><div><strong>{{ accounts.length }}</strong><span>厂商账号</span></div><div><strong>{{ providers.length }}</strong><span>支持厂商</span></div><div><strong>{{ records.length }}</strong><span>当前解析记录</span></div></div><a-segmented v-model:value="tab" :options="[{value:'domains',label:'域名与解析'},{value:'accounts',label:'DNS 厂商账号'}]" class="dns-tabs"/>
<div v-if="tab==='accounts'" class="vben-card"><ResourceTable :rows="accounts" :columns="accountColumns" :loading="loading"><template #cell-configured_secret_fields="{value}">{{ Array.isArray(value)?value.length:0 }} 项</template><template v-if="auth.canAny(['dns.manage'])" #actions="{row}"><a-button type="link" @click="editAccount(row as DNSAccount)">编辑</a-button><a-button type="link" @click="toggle('account',row as DNSAccount)">{{ row.is_active?'停用':'启用' }}</a-button><a-button type="link" danger @click="remove('account',row as DNSAccount)">删除</a-button></template></ResourceTable></div>
<div v-else class="domain-workspace vben-card"><aside><header><strong>域名</strong><small>{{ domains.length }} 个</small></header><button v-for="item in domains" :key="item.id" :class="{active:selectedID===item.id}" @click="selectedID=item.id"><Globe2/><span><strong>{{ item.name }}</strong><small>{{ item.account_name }}</small></span><i :class="{inactive:!item.is_active}"/></button></aside><main><div class="domain-heading"><div><h3>{{ selectedDomain?.name||'解析记录' }}</h3><p>{{ selectedDomain?.description||'选择域名查看厂商侧解析记录。' }}</p></div><div v-if="selectedDomain"><a-button :loading="testingID===selectedDomain.id" @click="testDomain(selectedDomain)">测试连接</a-button><a-button v-if="auth.canAny(['dns.manage'])" @click="editDomain(selectedDomain)">编辑域名</a-button><a-button v-if="auth.canAny(['dns.manage'])" type="primary" @click="newRecord"><Plus :size="15"/>添加记录</a-button></div></div><a-input v-model:value="query" allow-clear placeholder="筛选主机记录、类型或记录值" class="record-search"><template #prefix><Search :size="15"/></template></a-input><ResourceTable :rows="filteredRecords" :columns="recordColumns" :loading="recordsLoading"><template #cell-type="{value}"><a-tag color="blue">{{ value }}</a-tag></template><template #cell-ttl="{value}">{{ value===1?'自动':`${value} 秒` }}</template><template v-if="auth.canAny(['dns.manage'])" #actions="{row}"><a-button v-if="!row.read_only" type="link" @click="editRecord(row as DNSRecord)">编辑</a-button><a-button v-if="!row.read_only" type="link" danger @click="removeRecord(row as DNSRecord)">删除</a-button></template></ResourceTable></main></div>
<a-drawer v-model:open="accountOpen" :title="editingAccountID?'编辑 DNS 厂商账号':'添加 DNS 厂商账号'" width="620"><a-form layout="vertical"><div class="form-grid"><a-form-item label="账号名称" required><a-input v-model:value="accountForm.name"/></a-form-item><a-form-item label="DNS 厂商"><a-select :value="accountForm.provider" :disabled="Boolean(editingAccountID)" :options="providers.map(item=>({value:item.code,label:item.name}))" @change="changeProvider"/></a-form-item><a-form-item v-for="field in selectedProvider?.fields" :key="field.key" :class="{span2:field.multiline}" :label="field.label" :required="field.required&&!editingAccountID"><a-textarea v-if="field.multiline" v-model:value="accountForm.config[field.key]" :rows="6" :placeholder="field.secret&&editingAccountID?'留空表示保持原凭据':field.placeholder"/><a-input-password v-else-if="field.secret" v-model:value="accountForm.config[field.key]" :placeholder="editingAccountID?'留空表示保持原凭据':field.placeholder"/><a-input v-else v-model:value="accountForm.config[field.key]" :placeholder="field.placeholder"/><small>{{ field.help }}</small></a-form-item></div><a-button type="primary" block :loading="saving" @click="saveAccount">保存账号</a-button></a-form></a-drawer>
<a-modal v-model:open="domainOpen" :title="editingDomainID?'编辑域名':'添加域名'" :confirm-loading="saving" @ok="saveDomain"><a-form layout="vertical"><a-form-item label="厂商账号"><a-select v-model:value="domainForm.account_id" :options="accounts.filter(item=>item.is_active).map(item=>({value:item.id,label:item.name}))"/></a-form-item><a-form-item label="域名" required><a-input v-model:value="domainForm.name" placeholder="example.com"/></a-form-item><a-form-item label="说明"><a-input v-model:value="domainForm.description"/></a-form-item></a-form></a-modal>
<a-modal v-model:open="recordOpen" :title="editingRecordID?'编辑解析记录':'添加解析记录'" :confirm-loading="saving" @ok="saveRecord"><a-form layout="vertical"><div class="form-grid"><a-form-item label="主机记录"><a-input v-model:value="recordForm.name" placeholder="@ 或 www"/></a-form-item><a-form-item label="类型"><a-select v-model:value="recordForm.type" :options="recordTypes.map(value=>({value,label:value}))"/></a-form-item><a-form-item class="span2" label="记录值"><a-textarea v-model:value="recordForm.value" :rows="3"/></a-form-item><a-form-item label="TTL"><a-input-number v-model:value="recordForm.ttl" :min="1"/></a-form-item></div></a-form></a-modal></section></template>

<style scoped>.dns-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;margin-bottom:12px;border:1px solid var(--edo-border);border-radius:8px;background:var(--edo-border);overflow:hidden}.dns-summary div{padding:14px 18px;background:var(--edo-surface)}.dns-summary strong,.dns-summary span{display:block}.dns-summary strong{font-size:22px}.dns-summary span{color:var(--edo-muted);font-size:11px}.dns-tabs{margin-bottom:12px}.domain-workspace{display:grid;min-height:540px;grid-template-columns:230px 1fr;overflow:hidden}.domain-workspace>aside{border-right:1px solid var(--edo-border);background:var(--edo-surface-soft)}aside header{display:flex;justify-content:space-between;padding:14px;border-bottom:1px solid var(--edo-border)}aside button{display:grid;width:calc(100% - 12px);grid-template-columns:20px 1fr 7px;gap:9px;margin:4px 6px;padding:9px;border:0;border-radius:6px;background:transparent;cursor:pointer;text-align:left}aside button.active,aside button:hover{background:var(--edo-primary-soft)}aside button svg{width:17px;color:var(--edo-primary)}aside button span strong,aside button span small{display:block}aside button span small{color:var(--edo-muted);font-size:10px}aside button i{width:7px;height:7px;border-radius:50%;background:#29b670}aside button i.inactive{background:#aaa}.domain-workspace>main{min-width:0;padding:18px}.domain-heading{display:flex;align-items:flex-start;justify-content:space-between}.domain-heading h3,.domain-heading p{margin:0}.domain-heading p{color:var(--edo-muted)}.domain-heading>div:last-child{display:flex;gap:7px}.record-search{margin:16px 0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.span2{grid-column:1/-1}@media(max-width:720px){.dns-summary{grid-template-columns:repeat(2,1fr)}.domain-workspace{grid-template-columns:1fr}.domain-workspace>aside{max-height:220px;overflow:auto}.form-grid{grid-template-columns:1fr}.span2{grid-column:auto}}
</style>
