<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { message } from 'ant-design-vue'
import { Boxes, CloudCog, Plus, RefreshCw } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import { useAuthStore } from '@/stores/auth'

type Platform='docker'|'kubernetes';type Level='development'|'staging'|'production'
interface Environment extends ResourceRecord{id:string;name:string;description:string;platform:Platform;environment:Level;runtime_id:string;namespace:string;workload_name:string;container_name:string;rollout_timeout:number;is_active:boolean}
interface Runtime{id:string;name:string;host?:string;api_server?:string;default_namespace?:string;local?:boolean;is_active:boolean}
const auth=useAuthStore(),items=ref<Environment[]>([]),docker=ref<Runtime[]>([]),clusters=ref<Runtime[]>([]),selectedID=ref(''),formOpen=ref(false),editingID=ref(''),loading=ref(false),saving=ref(false),testing=ref(false)
const form=reactive({name:'',description:'',platform:'docker' as Platform,environment:'development' as Level,runtime_id:'',namespace:'default',workload_name:'',container_name:'',rollout_timeout:300})
const selected=computed(()=>items.value.find(item=>item.id===selectedID.value));const runtimeOptions=computed(()=>(form.platform==='docker'?docker.value:clusters.value).filter(item=>item.is_active).map(item=>({value:item.id,label:`${item.name} · ${item.local?'本地 Docker':item.host||item.api_server||'集群内连接'}`})))
const levelNames:Record<Level,string>={development:'开发',staging:'测试 / 预发布',production:'生产'}
function reset(){Object.assign(form,{name:'',description:'',platform:'docker',environment:'development',runtime_id:'',namespace:'default',workload_name:'',container_name:'',rollout_timeout:300});editingID.value=''}
async function refresh(){loading.value=true;try{const [a,b,c]=await Promise.all([client.get<{environments:Environment[]}>('/environments'),auth.canAny(['cluster.read'])?client.get<{endpoints:Runtime[]}>('/docker/endpoints'):null,auth.canAny(['cluster.read'])?client.get<{clusters:Runtime[]}>('/kubernetes/clusters'):null]);items.value=a.data.environments;docker.value=b?.data.endpoints||[];clusters.value=c?.data.clusters||[];if(!items.value.some(item=>item.id===selectedID.value))selectedID.value=items.value[0]?.id||''}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
function create(){reset();formOpen.value=true}
function edit(item:Environment){Object.assign(form,{name:item.name,description:item.description||'',platform:item.platform,environment:item.environment,runtime_id:item.runtime_id,namespace:item.namespace||'default',workload_name:item.workload_name,container_name:item.container_name||'',rollout_timeout:item.rollout_timeout});editingID.value=item.id;formOpen.value=true}
async function test(){if(!form.runtime_id){message.error('请选择发布连接');return}testing.value=true;try{await client.post(form.platform==='docker'?`/docker/endpoints/${form.runtime_id}/ping`:`/kubernetes/clusters/${form.runtime_id}/ping`);message.success('连接测试成功')}catch(error){message.error(apiErrorMessage(error))}finally{testing.value=false}}
async function save(){saving.value=true;try{const payload={...form,namespace:form.platform==='kubernetes'?form.namespace:'',container_name:form.platform==='kubernetes'?form.container_name:''};const result=editingID.value?await client.put<{environment:Environment}>(`/environments/${editingID.value}`,payload):await client.post<{environment:Environment}>('/environments',payload);selectedID.value=result.data.environment.id;message.success(editingID.value?'环境配置已更新':'环境已创建');formOpen.value=false;reset();await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
async function toggle(item:Environment){try{await client.patch(`/environments/${item.id}/status`,{active:!item.is_active});await refresh()}catch(error){message.error(apiErrorMessage(error))}}
onMounted(refresh)
</script>

<template><section><PageToolbar description="维护真实的发布目标。选择左侧环境后查看发布位置和工作负载，创建与编辑时列表始终保留。"><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button><a-button v-if="auth.canAny(['deployment.manage'])" type="primary" @click="create"><Plus :size="15"/>创建环境</a-button></PageToolbar><div class="master-detail vben-card"><aside><header><strong>环境列表</strong><small>{{ items.length }} 个发布目标</small></header><button v-for="item in items" :key="item.id" :class="{active:selectedID===item.id}" @click="selectedID=item.id"><component :is="item.platform==='docker'?Boxes:CloudCog"/><span><strong>{{ item.name }}</strong><small>{{ levelNames[item.environment] }} · {{ item.platform==='docker'?'Docker':'Kubernetes' }}</small></span><i :class="{inactive:!item.is_active}"/></button><a-empty v-if="!items.length&&!loading" :image="null" description="还没有发布环境"/></aside><main v-if="selected"><header class="detail-header"><div><span>{{ selected.platform==='docker'?'Docker 发布环境':'Kubernetes 发布环境' }}</span><h3>{{ selected.name }}</h3><p>{{ selected.description||'尚未填写环境说明' }}</p></div><div><a-tag :color="selected.is_active?'success':'default'">{{ selected.is_active?'已启用':'已停用' }}</a-tag><a-button v-if="auth.canAny(['deployment.manage'])" @click="edit(selected)">编辑</a-button><a-button v-if="auth.canAny(['deployment.manage'])" @click="toggle(selected)">{{ selected.is_active?'停用':'启用' }}</a-button></div></header><a-descriptions bordered :column="2"><a-descriptions-item label="环境级别">{{ levelNames[selected.environment] }}</a-descriptions-item><a-descriptions-item label="发布类型">{{ selected.platform==='docker'?'Docker':'Kubernetes' }}</a-descriptions-item><a-descriptions-item label="工作负载">{{ selected.workload_name||'未配置' }}</a-descriptions-item><a-descriptions-item label="发布超时">{{ selected.rollout_timeout }} 秒</a-descriptions-item><a-descriptions-item v-if="selected.platform==='kubernetes'" label="命名空间">{{ selected.namespace }}</a-descriptions-item><a-descriptions-item v-if="selected.platform==='kubernetes'" label="容器名称">{{ selected.container_name }}</a-descriptions-item></a-descriptions></main><div v-else class="empty-panel"><a-empty description="选择或创建发布环境"/></div></div>
<a-drawer v-model:open="formOpen" :title="editingID?'编辑环境':'创建环境'" width="620"><a-form layout="vertical"><div class="form-grid"><a-form-item label="环境名称" required><a-input v-model:value="form.name"/></a-form-item><a-form-item label="环境级别"><a-select v-model:value="form.environment" :options="Object.entries(levelNames).map(([value,label])=>({value,label}))"/></a-form-item><a-form-item class="span-2" label="说明"><a-input v-model:value="form.description"/></a-form-item><a-form-item label="发布类型"><a-select v-model:value="form.platform" :options="[{value:'docker',label:'Docker'},{value:'kubernetes',label:'Kubernetes'}]" @change="form.runtime_id=''"/></a-form-item><a-form-item label="运行时连接" required><a-select v-model:value="form.runtime_id" :options="runtimeOptions"/></a-form-item><a-form-item v-if="form.platform==='kubernetes'" label="命名空间"><a-input v-model:value="form.namespace"/></a-form-item><a-form-item label="工作负载名称" required><a-input v-model:value="form.workload_name"/></a-form-item><a-form-item v-if="form.platform==='kubernetes'" label="容器名称"><a-input v-model:value="form.container_name"/></a-form-item><a-form-item label="发布超时（秒）"><a-input-number v-model:value="form.rollout_timeout" :min="30" :max="3600"/></a-form-item></div><div class="drawer-actions"><a-button :loading="testing" @click="test">测试连接</a-button><a-button type="primary" :loading="saving" @click="save">保存</a-button></div></a-form></a-drawer></section></template>

<style scoped>.master-detail{display:grid;min-height:560px;grid-template-columns:270px 1fr;overflow:hidden}.master-detail>aside{border-right:1px solid var(--zrt-border);background:var(--zrt-surface-soft)}aside>header{display:flex;align-items:center;justify-content:space-between;padding:16px;border-bottom:1px solid var(--zrt-border)}aside>header small{color:var(--zrt-muted)}aside>button{display:grid;width:calc(100% - 12px);min-height:58px;align-items:center;grid-template-columns:25px 1fr 8px;gap:9px;margin:6px;padding:8px 10px;border:0;border-radius:6px;background:transparent;cursor:pointer;text-align:left}aside>button:hover,aside>button.active{background:var(--zrt-primary-soft)}aside>button svg{width:19px;color:var(--zrt-primary)}aside>button span strong,aside>button span small{display:block}aside>button span small{color:var(--zrt-muted);font-size:11px}aside>button i{width:7px;height:7px;border-radius:50%;background:#28b66e}aside>button i.inactive{background:#a8adb7}.master-detail>main{padding:24px}.detail-header{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:24px}.detail-header h3,.detail-header p{margin:0}.detail-header p,.detail-header span{color:var(--zrt-muted)}.detail-header>div:last-child{display:flex;align-items:center;gap:8px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.span-2{grid-column:1/-1}.drawer-actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:760px){.master-detail{grid-template-columns:1fr}.master-detail>aside{max-height:260px;border-right:0;border-bottom:1px solid var(--zrt-border)}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.detail-header{gap:12px;flex-direction:column}}
</style>
