<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { message } from 'ant-design-vue'
import { Plus, RefreshCw } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, type ResourceRecord } from '@/api/resources'
import ResourceTable from '@/components/ResourceTable.vue'
import { useAuthStore } from '@/stores/auth'

type ProviderType='ldap'|'generic_oauth'|'feishu'|'google'|'github'|'gitlab'
interface Provider extends ResourceRecord {id:string;type:ProviderType;name:string;display_name:string;is_active:boolean;auto_create:boolean;default_role_id:string;client_id:string;authorization_url:string;token_url:string;user_info_url:string;redirect_url:string;scopes:string;subject_field:string;username_field:string;nickname_field:string;email_field:string;email_verified_field:string;ldap_url:string;ldap_base_dn:string;ldap_bind_dn:string;ldap_user_filter:string;ldap_username_attribute:string;ldap_nickname_attribute:string;ldap_email_attribute:string;ldap_start_tls:boolean;allow_insecure:boolean}
interface Role {id:string;display_name:string}
const auth=useAuthStore(),items=ref<Provider[]>([]),roles=ref<Role[]>([]),loading=ref(false),saving=ref(false),open=ref(false),editingID=ref('')
const typeLabels:Record<ProviderType,string>={ldap:'LDAP',generic_oauth:'通用 OAuth',feishu:'飞书',google:'Google',github:'GitHub',gitlab:'GitLab'}
const form=reactive({type:'ldap' as ProviderType,name:'ldap',display_name:'企业 LDAP',is_active:true,auto_create:false,default_role_id:'',client_id:'',client_secret:'',authorization_url:'',token_url:'',user_info_url:'',redirect_url:'',scopes:'openid profile email',subject_field:'sub',username_field:'preferred_username',nickname_field:'name',email_field:'email',email_verified_field:'',ldap_url:'ldaps://ldap.example.com:636',ldap_base_dn:'',ldap_bind_dn:'',ldap_bind_password:'',ldap_user_filter:'(uid={username})',ldap_username_attribute:'uid',ldap_nickname_attribute:'displayName',ldap_email_attribute:'mail',ldap_start_tls:false,allow_insecure:false})
const isLDAP=computed(()=>form.type==='ldap')
const columns=[{key:'display_name',label:'名称'},{key:'type',label:'类型'},{key:'name',label:'内部标识'},{key:'auto_create',label:'自动创建用户'},{key:'is_active',label:'状态'}]
function defaults(type:ProviderType='ldap'){const name=type==='generic_oauth'?'company_oauth':type;Object.assign(form,{type,name,display_name:typeLabels[type],is_active:true,auto_create:false,default_role_id:'',client_id:'',client_secret:'',authorization_url:'',token_url:'',user_info_url:'',redirect_url:`${location.origin}/api/v1/auth/oauth/${name}/callback`,scopes:'openid profile email',subject_field:'sub',username_field:'preferred_username',nickname_field:'name',email_field:'email',email_verified_field:'',ldap_url:'ldaps://ldap.example.com:636',ldap_base_dn:'',ldap_bind_dn:'',ldap_bind_password:'',ldap_user_filter:'(uid={username})',ldap_username_attribute:'uid',ldap_nickname_attribute:'displayName',ldap_email_attribute:'mail',ldap_start_tls:false,allow_insecure:false})}
async function refresh(){loading.value=true;try{const [providersResult,rolesResult]=await Promise.all([client.get<{providers:Provider[]}>('/identity-providers'),client.get<{roles:Role[]}>('/roles').catch(()=>({data:{roles:[] as Role[]}}))]);items.value=providersResult.data.providers;roles.value=rolesResult.data.roles}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
function create(){editingID.value='';defaults();open.value=true}
function edit(item:Provider){editingID.value=item.id;Object.assign(form,item,{client_secret:'',ldap_bind_password:''});open.value=true}
async function save(){saving.value=true;try{const payload={...form,client_secret:form.client_secret||undefined,ldap_bind_password:form.ldap_bind_password||undefined};if(editingID.value)await client.put(`/identity-providers/${editingID.value}`,payload);else await client.post('/identity-providers',payload);message.success('登录方式已保存');open.value=false;await refresh()}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=false}}
async function toggle(item:Provider){try{await client.patch(`/identity-providers/${item.id}/status`,{is_active:!item.is_active});await refresh()}catch(error){message.error(apiErrorMessage(error))}}
function changeType(type:ProviderType){defaults(type)}
onMounted(refresh)
</script>

<template>
  <div class="identity-settings">
    <div class="identity-heading"><div><h3>登录方式</h3><p>接入企业目录或常用身份平台，密钥内容会加密保存。</p></div><div><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button><a-button v-if="auth.canAny(['identity.manage'])" type="primary" @click="create"><Plus :size="15"/>添加登录方式</a-button></div></div>
    <div class="vben-card"><ResourceTable :rows="items" :columns="columns" :loading="loading"><template #cell-type="{value}"><a-tag color="blue">{{ typeLabels[value as ProviderType]||value }}</a-tag></template><template v-if="auth.canAny(['identity.manage'])" #actions="{row}"><a-button type="link" @click="edit(row as Provider)">编辑</a-button><a-button type="link" @click="toggle(row as Provider)">{{ row.is_active?'停用':'启用' }}</a-button></template></ResourceTable></div>
    <a-drawer v-model:open="open" :title="editingID?'编辑登录方式':'添加登录方式'" width="680"><a-form layout="vertical"><a-form-item v-if="!editingID" label="类型"><a-segmented :value="form.type" :options="Object.entries(typeLabels).map(([value,label])=>({value,label}))" @change="(value:ProviderType)=>changeType(value)"/></a-form-item><div class="form-grid"><a-form-item label="显示名称" required><a-input v-model:value="form.display_name"/></a-form-item><a-form-item label="内部标识" required><a-input v-model:value="form.name" :disabled="Boolean(editingID)"/></a-form-item><a-form-item label="首次登录后的角色"><a-select v-model:value="form.default_role_id" allow-clear :options="roles.map(role=>({value:role.id,label:role.display_name}))"/></a-form-item><a-form-item label="用户策略"><a-space><a-checkbox v-model:checked="form.is_active">立即启用</a-checkbox><a-checkbox v-model:checked="form.auto_create">自动创建用户</a-checkbox></a-space></a-form-item></div>
      <template v-if="isLDAP"><a-divider>LDAP 连接</a-divider><div class="form-grid"><a-form-item label="服务器地址" required><a-input v-model:value="form.ldap_url"/></a-form-item><a-form-item label="用户目录" required><a-input v-model:value="form.ldap_base_dn"/></a-form-item><a-form-item label="查询账号 DN"><a-input v-model:value="form.ldap_bind_dn"/></a-form-item><a-form-item label="查询账号密码"><a-input-password v-model:value="form.ldap_bind_password" :placeholder="editingID?'留空表示不修改':''"/></a-form-item><a-form-item label="用户查询条件"><a-input v-model:value="form.ldap_user_filter"/></a-form-item><a-form-item label="用户名字段"><a-input v-model:value="form.ldap_username_attribute"/></a-form-item></div><a-checkbox v-model:checked="form.ldap_start_tls">使用 StartTLS</a-checkbox><a-checkbox v-model:checked="form.allow_insecure">允许明文 LDAP</a-checkbox></template>
      <template v-else><a-divider>OAuth / OIDC</a-divider><div class="form-grid"><a-form-item label="Client ID" required><a-input v-model:value="form.client_id"/></a-form-item><a-form-item label="Client Secret"><a-input-password v-model:value="form.client_secret" :placeholder="editingID?'留空表示不修改':''"/></a-form-item><a-form-item class="span-2" label="回调地址" required><a-input v-model:value="form.redirect_url"/></a-form-item><a-form-item class="span-2" label="授权地址" required><a-input v-model:value="form.authorization_url"/></a-form-item><a-form-item class="span-2" label="令牌地址" required><a-input v-model:value="form.token_url"/></a-form-item><a-form-item class="span-2" label="用户信息地址" required><a-input v-model:value="form.user_info_url"/></a-form-item><a-form-item label="Scopes"><a-input v-model:value="form.scopes"/></a-form-item><a-form-item label="用户唯一 ID 字段"><a-input v-model:value="form.subject_field"/></a-form-item></div><a-checkbox v-model:checked="form.allow_insecure">允许 HTTP（仅开发环境）</a-checkbox></template>
      <a-button type="primary" block :loading="saving" class="save-provider" @click="save">保存登录方式</a-button></a-form></a-drawer>
  </div>
</template>

<style scoped>.identity-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.identity-heading h3,.identity-heading p{margin:0}.identity-heading p{margin-top:4px;color:var(--zrt-muted)}.identity-heading>div:last-child{display:flex;gap:8px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px}.span-2{grid-column:1/-1}.save-provider{margin-top:22px}@media(max-width:650px){.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}}
</style>
