<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { Boxes, Container, Network, Plus, RefreshCw, ServerCog, TerminalSquare } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage, getResources, type ResourceRecord } from '@/api/resources'
import JsonCreateDrawer from '@/components/JsonCreateDrawer.vue'
import PageToolbar from '@/components/PageToolbar.vue'
import ResourceTable from '@/components/ResourceTable.vue'
import TerminalDrawer from '@/components/TerminalDrawer.vue'
import { useAuthStore } from '@/stores/auth'

const route=useRoute(),router=useRouter(),auth=useAuthStore(),docker=ref<ResourceRecord[]>([]),clusters=ref<ResourceRecord[]>([]),containers=ref<ResourceRecord[]>([]),pods=ref<ResourceRecord[]>([]),loading=ref(false),resourceLoading=ref(false),createOpen=ref(false),createKind=ref<'docker'|'kubernetes'>('docker'),namespace=ref('default'),terminal=ref({open:false,title:'',path:''})
const selectedNode=computed(()=>String(route.query.node||'overview')),selectedDockerID=computed(()=>selectedNode.value.startsWith('docker:')?selectedNode.value.slice(7):''),selectedClusterID=computed(()=>selectedNode.value.startsWith('kubernetes:')?selectedNode.value.slice(11):''),selectedDocker=computed(()=>docker.value.find(item=>String(item.id)===selectedDockerID.value)),selectedCluster=computed(()=>clusters.value.find(item=>String(item.id)===selectedClusterID.value))
const createExample=computed(()=>createKind.value==='docker'?{name:'remote-docker',host:'server.example.com',port:22,username:'zrt',auth_type:'private_key',private_key:'请粘贴私钥',password:null}:{name:'production-k8s',mode:'kubeconfig',default_namespace:'default',kubeconfig:'请粘贴不包含 exec 插件和外部文件引用的 kubeconfig'})
async function refresh(){loading.value=true;try{[docker.value,clusters.value]=await Promise.all([getResources('/docker/endpoints','endpoints'),getResources('/kubernetes/clusters','clusters')])}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
function choose(node:string){void router.replace({query:{node}})}
async function loadRuntime(){resourceLoading.value=true;try{if(selectedDockerID.value)containers.value=await getResources(`/docker/endpoints/${selectedDockerID.value}/containers?all=true`,'containers');if(selectedClusterID.value)pods.value=await getResources(`/kubernetes/clusters/${selectedClusterID.value}/pods?namespace=${encodeURIComponent(namespace.value)}`,'pods')}catch(error){message.error(apiErrorMessage(error))}finally{resourceLoading.value=false}}
async function ping(kind:'docker'|'kubernetes',id:string){try{await client.post(kind==='docker'?`/docker/endpoints/${id}/ping`:`/kubernetes/clusters/${id}/ping`);message.success('连接检查通过')}catch(error){message.error(apiErrorMessage(error))}}
function openCreate(kind:'docker'|'kubernetes'){createKind.value=kind;createOpen.value=true}
function openTerminal(title:string,path:string){terminal.value={open:true,title,path}}
watch([selectedDockerID,selectedClusterID],()=>{if(selectedCluster.value)namespace.value=String(selectedCluster.value.default_namespace||'default');if(selectedDockerID.value||selectedClusterID.value)void loadRuntime()})
onMounted(()=>{void refresh();if(route.query.create==='ssh')openCreate('docker');if(route.query.create==='kubernetes')openCreate('kubernetes')})
</script>

<template><section><PageToolbar description="按 Docker、Kubernetes 和具体连接逐层浏览；只在选择运行时后加载容器或 Pod。"><a-button :loading="loading" @click="refresh"><RefreshCw :size="15"/>刷新</a-button></PageToolbar><div class="infra-workspace vben-card"><aside><header><strong>资源树</strong><small>{{ docker.length+clusters.length }} 个连接</small></header><button :class="{active:selectedNode==='overview'}" @click="choose('overview')"><Network/><span>资源概览</span></button><section><h4><Boxes/>Docker <a-badge :count="docker.length"/></h4><button :class="{active:selectedNode==='docker-connections'}" @click="choose('docker-connections')"><ServerCog/><span>连接管理</span></button><button v-for="item in docker" :key="String(item.id)" :class="{active:selectedNode===`docker:${item.id}`}" @click="choose(`docker:${item.id}`)"><i :class="{inactive:item.is_active===false}"/><span>{{ item.name }}</span><small>{{ item.local?'本地':'SSH' }}</small></button></section><section><h4><Container/>Kubernetes <a-badge :count="clusters.length"/></h4><button :class="{active:selectedNode==='kubernetes-clusters'}" @click="choose('kubernetes-clusters')"><ServerCog/><span>集群管理</span></button><button v-for="item in clusters" :key="String(item.id)" :class="{active:selectedNode===`kubernetes:${item.id}`}" @click="choose(`kubernetes:${item.id}`)"><i :class="{inactive:item.is_active===false}"/><span>{{ item.name }}</span><small>{{ item.mode }}</small></button></section></aside><main>
<div v-if="selectedNode==='overview'" class="infra-overview"><h3>运行时连接</h3><p>选择具体连接后，再查看容器、Pod 与可用终端。</p><div><button @click="choose('docker-connections')"><Boxes/><strong>{{ docker.length }}</strong><span>Docker 连接</span></button><button @click="choose('kubernetes-clusters')"><Container/><strong>{{ clusters.length }}</strong><span>Kubernetes 集群</span></button></div></div>
<template v-else-if="selectedNode==='docker-connections'||selectedNode==='kubernetes-clusters'"><header class="infra-heading"><div><h3>{{ selectedNode==='docker-connections'?'Docker 连接管理':'Kubernetes 集群管理' }}</h3><p>{{ selectedNode==='docker-connections'?'本地连接使用 ZRT 构建运行时；远程主机通过 SSH 接入。':'统一管理集群凭据与默认命名空间。' }}</p></div><a-button v-if="auth.canAny(['cluster.manage'])" type="primary" @click="openCreate(selectedNode==='docker-connections'?'docker':'kubernetes')"><Plus :size="15"/>新增连接</a-button></header><ResourceTable :rows="selectedNode==='docker-connections'?docker:clusters" :columns="selectedNode==='docker-connections'?[{key:'name',label:'名称'},{key:'host',label:'连接地址'},{key:'local',label:'本地运行时'},{key:'is_active',label:'状态'}]:[{key:'name',label:'名称'},{key:'mode',label:'模式'},{key:'api_server',label:'API Server'},{key:'default_namespace',label:'默认命名空间'}]" :loading="loading"><template #actions="{row}"><a-button type="link" @click="choose(`${selectedNode==='docker-connections'?'docker':'kubernetes'}:${row.id}`)">打开</a-button><a-button v-if="auth.canAny(['cluster.manage'])" type="link" @click="ping(selectedNode==='docker-connections'?'docker':'kubernetes',String(row.id))">检查</a-button></template></ResourceTable></template>
<template v-else-if="selectedDocker"><header class="runtime-heading"><div><span>Docker 连接</span><h3>{{ selectedDocker.name }}</h3><p>{{ selectedDocker.local?'本地 Docker 运行时':selectedDocker.host }}</p></div><a-button @click="ping('docker',selectedDockerID)">检查连接</a-button></header><ResourceTable :rows="containers" :columns="[{key:'names',label:'名称'},{key:'image',label:'镜像'},{key:'state',label:'状态'},{key:'status',label:'详情'}]" :loading="resourceLoading"><template v-if="auth.canAny(['terminal.open'])" #actions="{row}"><a-button v-if="row.state==='running'" type="link" @click="openTerminal(`Docker · ${row.names}`,`/api/v1/terminals/docker/${encodeURIComponent(selectedDockerID)}/containers/${encodeURIComponent(String(row.id))}/ws`)"><TerminalSquare :size="15"/>终端</a-button></template></ResourceTable></template>
<template v-else-if="selectedCluster"><header class="runtime-heading"><div><span>Kubernetes 集群</span><h3>{{ selectedCluster.name }}</h3><p>{{ selectedCluster.api_server||'集群内连接' }}</p></div><div><a-input v-model:value="namespace" style="width:160px"/><a-button :loading="resourceLoading" @click="loadRuntime">加载命名空间</a-button></div></header><ResourceTable :rows="pods" :columns="[{key:'name',label:'Pod'},{key:'namespace',label:'命名空间'},{key:'phase',label:'阶段'},{key:'containers',label:'容器'}]" :loading="resourceLoading"><template v-if="auth.canAny(['terminal.open'])" #actions="{row}"><a-button v-for="containerName in (row.phase==='Running'&&Array.isArray(row.containers)?row.containers:[])" :key="String(containerName)" type="link" @click="openTerminal(`Pod · ${row.name} / ${containerName}`,`/api/v1/terminals/kubernetes/${encodeURIComponent(selectedClusterID)}/namespaces/${encodeURIComponent(String(row.namespace))}/pods/${encodeURIComponent(String(row.name))}/containers/${encodeURIComponent(String(containerName))}/ws`)">{{ containerName }}</a-button></template></ResourceTable></template>
</main></div><JsonCreateDrawer v-model:open="createOpen" :title="createKind==='docker'?'远程 Docker 连接':'Kubernetes 集群'" :endpoint="createKind==='docker'?'/docker/endpoints':'/kubernetes/clusters'" :example="createExample" @created="refresh"/><TerminalDrawer v-model:open="terminal.open" :title="terminal.title" :path="terminal.path"/></section></template>

<style scoped>.infra-workspace{display:grid;min-height:620px;grid-template-columns:245px 1fr;overflow:hidden}.infra-workspace>aside{border-right:1px solid var(--zrt-border);background:var(--zrt-surface-soft)}aside header{display:flex;justify-content:space-between;padding:15px;border-bottom:1px solid var(--zrt-border)}aside header small{color:var(--zrt-muted)}aside section h4{display:flex;align-items:center;gap:7px;margin:17px 14px 5px;color:var(--zrt-muted);font-size:12px}aside section h4 svg{width:16px}aside button{display:grid;width:calc(100% - 12px);min-height:38px;align-items:center;grid-template-columns:20px 1fr auto;gap:8px;margin:2px 6px;padding:0 10px;border:0;border-radius:6px;background:transparent;cursor:pointer;text-align:left}aside button:hover,aside button.active{color:var(--zrt-primary);background:var(--zrt-primary-soft)}aside button svg{width:16px}aside button i{width:7px;height:7px;border-radius:50%;background:#27b56c}aside button i.inactive{background:#a9adb5}aside button small{color:var(--zrt-muted);font-size:10px}.infra-workspace>main{min-width:0;padding:20px}.infra-overview>p{color:var(--zrt-muted)}.infra-overview>div{display:grid;grid-template-columns:1fr 1fr;gap:14px}.infra-overview button{display:grid;min-height:150px;place-items:center;border:1px solid var(--zrt-border);border-radius:8px;background:var(--zrt-surface);cursor:pointer}.infra-overview button:hover{border-color:var(--zrt-primary)}.infra-overview button svg{width:30px;color:var(--zrt-primary)}.infra-overview button strong{font-size:28px}.infra-heading,.runtime-heading{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:18px}.infra-heading h3,.infra-heading p,.runtime-heading h3,.runtime-heading p{margin:0}.infra-heading p,.runtime-heading p,.runtime-heading span{color:var(--zrt-muted)}.runtime-heading>div:last-child{display:flex;gap:8px}@media(max-width:760px){.infra-workspace{grid-template-columns:1fr}.infra-workspace>aside{max-height:280px;overflow:auto;border-right:0;border-bottom:1px solid var(--zrt-border)}.infra-overview>div{grid-template-columns:1fr}}
</style>
