<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Modal, message } from 'ant-design-vue'
import { Database, KeyRound, RefreshCw, ShieldCheck, Trash2 } from 'lucide-vue-next'

import client from '@/api/client'
import { apiErrorMessage } from '@/api/resources'
import PageToolbar from '@/components/PageToolbar.vue'
import IdentityProvidersView from '@/views/IdentityProvidersView.vue'
import { useAuthStore } from '@/stores/auth'

interface ToggleSetting{enabled:boolean;version:number}
interface WebhookSetting extends ToggleSetting{path_template:string;max_body_bytes:number;providers:string[];events:string[]}
interface LockoutSetting extends ToggleSetting{max_failures:number;window_seconds:number}
interface RetentionSetting extends ToggleSetting{pipeline_log_days:number;audit_log_days:number}
interface MigrationStatus{id?:string;source_driver:string;target_driver?:string;state:'idle'|'preparing'|'migrating'|'succeeded'|'failed';message:string;total_tables:number;completed_tables:number;copied_rows:number;requires_restart:boolean}
interface TestResult{test_token:string;driver:string;expires_at:string}

const route=useRoute(),router=useRouter(),auth=useAuthStore(),loading=ref(false),saving=ref(''),passwordSaving=ref(false)
const webhook=ref<WebhookSetting|null>(null),lockout=ref<LockoutSetting|null>(null),retention=ref<RetentionSetting|null>(null),migration=ref<MigrationStatus|null>(null),testResult=ref<TestResult|null>(null)
const password=reactive({current:'',next:'',confirm:''}),database=reactive({driver:'mysql' as 'mysql'|'postgres',dsn:'',confirmation:''})
let migrationTimer=0
const canConfig=computed(()=>auth.canAny(['config.read'])),canManage=computed(()=>auth.canAny(['config.manage'])),canIdentity=computed(()=>auth.canAny(['identity.read'])),isSuperuser=computed(()=>Boolean(auth.user?.is_superuser))
const sections=computed(()=>[{key:'account',label:'修改密码'},...(canConfig.value?[{key:'general',label:'安全与接入'},{key:'logs',label:'日志保留'}]:[]),...(isSuperuser.value?[{key:'database',label:'数据库迁移'}]:[]),...(canIdentity.value?[{key:'identity',label:'登录方式'}]:[])])
const active=computed(()=>sections.value.some(item=>item.key===route.query.section)?String(route.query.section):'account')
function select(value:string){void router.replace({query:value==='account'?{}:{section:value}})}
async function load(){if(!canConfig.value)return;loading.value=true;try{const [a,b,c]=await Promise.all([client.get<WebhookSetting>('/settings/external-git-webhook'),client.get<LockoutSetting>('/settings/login-lockout'),client.get<RetentionSetting>('/settings/log-retention')]);webhook.value=a.data;lockout.value=b.data;retention.value=c.data}catch(error){message.error(apiErrorMessage(error))}finally{loading.value=false}}
async function loadMigration(){if(!isSuperuser.value)return;try{migration.value=(await client.get<MigrationStatus>('/settings/database-migration')).data}catch(error){message.error(apiErrorMessage(error))}}
async function toggle(kind:'webhook'|'lockout'){const current=kind==='webhook'?webhook.value:lockout.value;if(!current||!canManage.value)return;saving.value=kind;try{const path=kind==='webhook'?'/settings/external-git-webhook':'/settings/login-lockout';const response=await client.put(path,{enabled:!current.enabled,expected_version:current.version});if(kind==='webhook')webhook.value=response.data;else lockout.value=response.data;message.success('设置已保存')}catch(error){message.error(apiErrorMessage(error));await load()}finally{saving.value=''}}
async function changePassword(){if(password.next.length<12){message.error('新密码至少需要 12 个字符。');return}if(password.next!==password.confirm){message.error('两次输入的新密码不一致。');return}passwordSaving.value=true;try{await client.put('/auth/password',{current_password:password.current,new_password:password.next});location.assign('/login?reason=password_changed')}catch(error){message.error(apiErrorMessage(error))}finally{passwordSaving.value=false}}
async function saveRetention(){if(!retention.value)return;saving.value='retention';try{retention.value=(await client.put<RetentionSetting>('/settings/log-retention',{...retention.value,expected_version:retention.value.version})).data;message.success('日志保留策略已保存')}catch(error){message.error(apiErrorMessage(error));await load()}finally{saving.value=''}}
function cleanup(){Modal.confirm({title:'立即清理过期日志？',content:'超过当前保留时间的流水线日志和审计日志会被永久删除。',okType:'danger',okText:'立即清理',async onOk(){saving.value='cleanup';try{const result=(await client.post<{pipeline_logs_deleted:number;audit_logs_deleted:number}>('/settings/log-retention/cleanup')).data;message.success(`已删除 ${result.pipeline_logs_deleted} 条流水线日志和 ${result.audit_logs_deleted} 条审计日志`)}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=''}}})}
async function testDatabase(){if(!database.dsn.trim()){message.error('请输入目标数据库连接串。');return}saving.value='db-test';try{testResult.value=(await client.post<TestResult>('/settings/database-migration/test',{driver:database.driver,dsn:database.dsn})).data;database.confirmation='';message.success('连接成功，且目标库为空库。测试结果 10 分钟内有效。')}catch(error){testResult.value=null;message.error(apiErrorMessage(error))}finally{saving.value=''}}
async function startMigration(){if(!testResult.value||database.confirmation!=='MIGRATE')return;saving.value='db-start';try{migration.value=(await client.post<MigrationStatus>('/settings/database-migration',{driver:database.driver,dsn:database.dsn,test_token:testResult.value.test_token,confirmation:database.confirmation})).data;testResult.value=null;message.success('数据库迁移已启动')}catch(error){message.error(apiErrorMessage(error))}finally{saving.value=''}}
watch(()=>migration.value?.state,(state)=>{clearInterval(migrationTimer);if(state==='preparing'||state==='migrating')migrationTimer=window.setInterval(loadMigration,1500)})
onMounted(()=>{void load();void loadMigration()});onBeforeUnmount(()=>clearInterval(migrationTimer))
</script>

<template>
  <section>
    <PageToolbar description="管理当前账户、日志保留、登录安全和数据库迁移。"><a-button v-if="active==='general'||active==='logs'" :loading="loading" @click="load"><RefreshCw :size="15"/>刷新</a-button></PageToolbar>
    <a-segmented :value="active" :options="sections.map(item=>({value:item.key,label:item.label}))" class="settings-tabs" @change="(value:string)=>select(value)"/>
    <article v-if="active==='account'" class="setting-card vben-card"><header><span><KeyRound/></span><div><h3>修改当前账户密码</h3><p>修改成功后，所有设备上的旧会话都会失效，并返回登录界面。</p></div></header><a-form layout="vertical" class="settings-form" @finish="changePassword"><a-form-item label="当前密码" required><a-input-password v-model:value="password.current" autocomplete="current-password"/></a-form-item><a-form-item label="新密码" required><a-input-password v-model:value="password.next" autocomplete="new-password"/></a-form-item><a-form-item label="再次输入新密码" required><a-input-password v-model:value="password.confirm" autocomplete="new-password"/></a-form-item><a-button type="primary" html-type="submit" :loading="passwordSaving">修改密码</a-button></a-form></article>
    <template v-if="active==='general'">
      <article class="setting-card vben-card"><header><span><ShieldCheck/></span><div><h3>Git Webhook API</h3><p>允许外部 Git 平台把代码事件发送给 ZRT，并继续执行签名校验与投递去重。</p></div><a-switch :checked="webhook?.enabled" :loading="saving==='webhook'" :disabled="!canManage" @change="toggle('webhook')"/></header><dl><div><dt>请求地址</dt><dd><code>{{ webhook?.path_template||'/api/v1/webhooks/git/{repository_id}' }}</code></dd></div><div><dt>支持平台</dt><dd>{{ webhook?.providers?.join('、')||'GitHub、GitLab、Gitea、Gitee、普通 Git' }}</dd></div><div><dt>请求上限</dt><dd>{{ Math.round((webhook?.max_body_bytes||2097152)/1048576) }} MiB</dd></div></dl></article>
      <article class="setting-card vben-card"><header><span><ShieldCheck/></span><div><h3>登录失败锁定</h3><p>默认关闭；开启后，同一用户名和来源地址连续失败会被暂时锁定。</p></div><a-switch :checked="lockout?.enabled" :loading="saving==='lockout'" :disabled="!canManage" @change="toggle('lockout')"/></header><dl><div><dt>触发阈值</dt><dd>{{ lockout?.max_failures||5 }} 次失败</dd></div><div><dt>锁定时间</dt><dd>{{ Math.round((lockout?.window_seconds||900)/60) }} 分钟</dd></div><div><dt>计数维度</dt><dd>用户名与来源地址</dd></div></dl></article>
    </template>
    <article v-if="active==='logs'&&retention" class="setting-card vben-card"><header><span><Trash2/></span><div><h3>日志保留与自动清理</h3><p>分别控制流水线执行日志和审计日志的保留时间，新安装默认不自动清理。</p></div><a-switch v-model:checked="retention.enabled" :disabled="!canManage"/></header><div class="settings-form two"><a-form-item label="流水线日志保留天数"><a-input-number v-model:value="retention.pipeline_log_days" :min="1" :max="3650" :disabled="!canManage"/></a-form-item><a-form-item label="审计日志保留天数"><a-input-number v-model:value="retention.audit_log_days" :min="1" :max="3650" :disabled="!canManage"/></a-form-item></div><a-alert type="warning" show-icon message="立即清理无法撤销，但不会删除流水线运行、发布记录或用户数据。"/><footer><a-button danger :disabled="!canManage||!retention.enabled" :loading="saving==='cleanup'" @click="cleanup">立即清理</a-button><a-button type="primary" :disabled="!canManage" :loading="saving==='retention'" @click="saveRetention">保存设置</a-button></footer></article>
    <article v-if="active==='database'&&isSuperuser" class="setting-card vben-card"><header><span><Database/></span><div><h3>SQLite 迁移到 MySQL / PostgreSQL</h3><p>目标库必须为空；连接串只用于本次测试与迁移，不会保存或记录。</p></div><a-tag :color="migration?.state==='succeeded'?'success':migration?.state==='failed'?'error':migration?.state==='migrating'?'processing':'default'">{{ migration?.state||'idle' }}</a-tag></header><a-descriptions bordered size="small" :column="4"><a-descriptions-item label="当前数据库">{{ migration?.source_driver?.toUpperCase()||'—' }}</a-descriptions-item><a-descriptions-item label="目标数据库">{{ migration?.target_driver?.toUpperCase()||'—' }}</a-descriptions-item><a-descriptions-item label="进度">{{ migration?.completed_tables||0 }} / {{ migration?.total_tables||0 }} 表</a-descriptions-item><a-descriptions-item label="已复制">{{ migration?.copied_rows||0 }} 行</a-descriptions-item></a-descriptions><a-alert type="error" show-icon class="migration-alert" message="迁移完成后必须停止当前服务，切换 ZRT_DATABASE_DRIVER / ZRT_DATABASE_DSN 并重启；禁止新旧库同时写入。"/><div class="database-form"><a-select v-model:value="database.driver" :options="[{value:'mysql',label:'MySQL 8+'},{value:'postgres',label:'PostgreSQL 14+'}]"/><a-input-password v-model:value="database.dsn" autocomplete="off" placeholder="目标数据库连接串" @change="testResult=null"/><a-button :loading="saving==='db-test'" @click="testDatabase">测试连接</a-button><a-input v-model:value="database.confirmation" :disabled="!testResult" placeholder="输入 MIGRATE"/><a-button type="primary" danger :disabled="!testResult||database.confirmation!=='MIGRATE'" :loading="saving==='db-start'" @click="startMigration">开始迁移</a-button></div><p class="migration-message">{{ migration?.message }}</p></article>
    <IdentityProvidersView v-if="active==='identity'"/>
  </section>
</template>

<style scoped>.settings-tabs{margin-bottom:14px}.setting-card{margin-bottom:14px;padding:21px}.setting-card header{display:flex;align-items:center;gap:14px}.setting-card header>span:first-child{display:grid;width:40px;height:40px;place-items:center;border-radius:7px;color:var(--zrt-primary);background:var(--zrt-primary-soft)}.setting-card header svg{width:20px}.setting-card header>div{min-width:0;flex:1}.setting-card h3,.setting-card p{margin:0}.setting-card p{margin-top:3px;color:var(--zrt-muted)}.settings-form{max-width:620px;margin-top:20px}.settings-form.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}dl{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin:20px 0 0;background:var(--zrt-border)}dl>div{padding:14px;background:var(--zrt-surface)}dt{color:var(--zrt-muted);font-size:11px}dd{margin:5px 0 0}.setting-card footer{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.migration-alert{margin:18px 0}.database-form{display:grid;grid-template-columns:170px minmax(260px,1fr) auto 160px auto;gap:8px}.migration-message{margin-top:14px!important}@media(max-width:850px){.database-form{grid-template-columns:1fr}.settings-form.two,dl{grid-template-columns:1fr}.setting-card header{align-items:flex-start;flex-wrap:wrap}}
</style>
